# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'MovieSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieSearchApp
  pod 'RxSwift', '6.5.0'
	pod 'RxCocoa', '6.5.0'
	pod 'SnapKit', '~> 5.6.0'
	pod 'Alamofire', '~> 5.5'
	pod 'Kingfisher', '~> 7.0'

end
